### ISSUE TITLE
Forums plugin?

### ISSUE THREAD

**Issue by loosebruce** [forkcms/forkcms#1036]
I've been lurking through the forums and seen hints of a ForkCMS forum being in the works. 

Can this be confirmed if ForkCMS or someone else is making a plugin, if not I will try integrating another forum to ForkCMS

**Comment by WouterSioen** [comment]
I think @guytarded was working on something like this?

**Comment by jessedobbelaere** [comment]
The [Fork forum](www.fork-cms.com/community/forum) is a custom module made for the website but it has yet to be open-sourced/released on github... That was the plan at first? I think @Diewy can help. Maybe put a raw version on github so we can do some bugfixing. (I actually have a list of bugs/improvements to the fork forum module laying around until it's released on github)

**Comment by guytarded** [comment]
@WouterSioen i dumped the plan as @Diewy made one and it was going to be released opensource :)

**Comment by loosebruce** [comment]
Cool, I will keep my eyes on this as I was trying to integrate phpBB but I will wait.

**Comment by jessedobbelaere** [comment]
If you want to use phpBB I would say: go ahead, because I don't know if Diewy is going to release it in the next few months or later. (Maybe the code is already outdated, much work to upgrade and clean-up or too specific for the fork cms website.) And some bugs still need fixing too I think, so it's not that "it just works" after install I guess.

**Comment by Diewy** [comment]
Here you go guys: https://github.com/Diewy/forkcms-module-forum
