### ISSUE TITLE
Feature: Upload logo (Dark & Light)

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1061]
Hi, i would suggest to implement this feature. I think should be good to have 2 logos uploaded through Settings and later parsed to templates with global variable SITE_LOGO_DARK and SITE_LOGO_LIGHT. I could implement this, just want to discuss.

**Comment by jessedobbelaere** [comment]
Hmm I think it's best to use a logo in the css of the theme that you're using, and when you use a dark template you can set a "dark" css class that makes your css load a different logo.

**Comment by vytenizs** [comment]
I wish to use logo on admin side, instead of site title. For emails sent. And there are lots of uses.

**Comment by jeroendesloovere** [comment]
Hi @vytenizs,
I must agree that I sometimes had the same feeling like you, "a centralized logo variable" would be awesome!!! But... things have changed so much. Retina displays (@2x), 5K displays (@3x) ... And use cases that differ per client, (different) (responsive) mail templates, header with big logo, footer with small logo or icon, or reverse, ... There is no straight forward line in that. Everything depends on the Design from the Designer.

Logo sizes also differ per client (square, rectangle, portrait, landscape, ...). So it is not possible to add a size to the upload that works out like you want it. I agree with @jessedobbelaere, that if you really want to do this, you should add it to the CSS theme and HTML mail templates.

I'm closing this one because w'll never find out a solution that fits everyone's needs.

**Comment by vytenizs** [comment]
Yes but in the end, logo is a square or rectangular. It can be used on emails, generated PDFs, admin side and lots of other places. For retina screens and others you could upload vector logo and convert it into several different sizes. And yes several logo options should be available. Dark logo, light logo, documents logo for example. Or even logo manager if you need so much customization... But in most cases it would be a great feature and simple websites would appreciate it... And it is not so big feature, because if you want to create themes market like WP did (ofc its a fucking bad shit), but everyone that downloads theme would have to make code changes to change logo. This is bad for simple user in any cases.

**Comment by jeroendesloovere** [comment]
@vytenizs 
What could work:
- A backend action with multiple '.svg' upload fields. Each .svg should require a "name", examples: 'logo_default', 'logo@2x', 'logo@3x', 'icon_default', 'icon_black', 'icon_white', ...
- Add a Template Modifier to accept something like {$var|getimage:'logo_default','320x320'},  {$var|getimage:'logo@2x','60x60'} and that functionality should on the fly generate an image with that size dimensions using the .svg. Using some caching here could be handy.

**Comment by vytenizs** [comment]
Exactly my thoughts. Ofc .svg should not go straight into website and should be generated, but not everyone have their logos in .svg so there should be an option to upload only some logos. First of all we need two logos DARK and LIGHT and then we need to split them into several generated ones for example: logo_dark@2x logo_dark@3x logo_dark. And when u use modifier 320x320 it caches generated 320x320 image for later use. Something like that. But this feature is user friendly because if simple user installs theme it will definitely want to change logo to its own and for that user will need to modify template. So think about this carefully, because it user experience you are playing with :) Personally i prefer your way, but in users perspective i dunno if its a good way... So think about this carefully. :)

**Comment by WouterSioen** [comment]
This is part of the theme development and isn't meant to be done in the core of Fork.
