### ISSUE TITLE
Make date.timezone configurable in paramaters.yml

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1075]
date.timezone setting is scattered between Init.php of Backend, Frontend and API, isn't it better to add it to parameters.yml ?

**Comment by WouterSioen** [comment]
Normally, your timezone should be set in your php.ini file. We just provide a fallback for when there isn't a timezone set in your servers configuration.

I don't think it should be in the parameters file. I don't even think this fallback should be present in the codebase, since a server without timezone in the php.ini is just a badly setup server, and the warnings shouldn't be supressed by adding a fallback. But thats just my opinion ;)

**Comment by ghazispeakserve** [comment]
And what if we put it the .htaccess file? Isn't it more natural?

**Comment by WouterSioen** [comment]
From PHP5.3, php throws warnings when you don't have date.timezone in your php.ini file. That's a big indication that you should add it in your php.ini file, and not in your .htaccess file or in your php code.
