### ISSUE TITLE
The New Mailmotor

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1164]
Hi,

At the [Last Fork CMS Meetup](http://www.meetup.com/Fork-CMS/events/220501469/) I talked to some Fork CMS developers (@diewy, @thijzer, @ikoene) about refactoring the Mailmotor to support any Mail engine available.

Since I already tried to [refactor mailmotor to support multiple mail engines like f.e. Mailchimp, next to the already integrated CampaignMonitor](https://github.com/siesqo/fork-cms-module-mailmotor). I was almost finished integrating everything, but I still came across to [unsolvable problems/issues](https://github.com/siesqo/fork-cms-module-mailmotor/issues) like f.e. non-existing functionality and the biggest part - maintainability.

So this is my call to all @forkcms/owners and @forkcms/moderators if we could talk about reducing the mailmotor to it simple basic functionality like:
- Subscribe/Unsubscribe subscribers from any external mail engine

And not:
- Storing subscribers in our own database
- Creating and sending mails. Which is something that can be discussed about.
  Yes, it is so cool if the client can do this, but the downside is maintainability and the very low use case.
  It is often used by marketing to pull new clients in. But it is rarely used.

Why downsizing?

We would attract more customers - willing to try Fork CMS - since they can use the mail engine they like.

What do you think about this?
Your opinion will be fully appreciated.
# 

Features overview:

**Frontend**
- [x] Subscribe widget
- [x] Unsubscribe widget

**Backend**
- Dashboard
  - [ ] Widget for subscriptions/unsubscriptions
  - [ ] v2: Widget for list growth
- Mailmotor
  - [ ] v2: Statistics for campaigns.
- Settings
  - [ ] Checkbox: "Add a first/last name field in Subscribe form"

**Comment by jessedobbelaere** [comment]
I like the idea. I never used the MailMotor module because I only had experience with Mailchimp. 

A stripped version of Mailmotor would be great, with multiple services such as Mailchimp & Campaign Monitor and the possibility to easily add another service in the future. Features like a subscribe/unsubscribe form are essential (maybe offer 2-3 different layouts: an e-mail only form, name and e-mail form, etc.), and maybe a dashboard displaying the most common stats + fork dashboard widget.

**Comment by jeroendesloovere** [comment]
@jessedobbelaere Can you be a bit more specific about what you want in the backend widgets?
So I can add your suggestions to the features overview.

**Comment by jessedobbelaere** [comment]
Just the basics: 

* A backend forkcms Dashboard widget with a few metrics (like the [old Mailmotor module had](https://cloud.githubusercontent.com/assets/4991088/6573083/bfd49c1e-c717-11e4-86d1-66b285109b45.png)). 
* A mailmotor dashboard with some graphs and stats for the campaign (a page like the analytics module has). I like the [List Growth chart](https://i.imgur.com/mlqfJMY.png). Other things: keep an eye on the % opened, % unopened, # clicks, #delivered, #unsubscribed, #bounced for the most recent campaign. Mailmotor probably had a dashboard/statistics page too? But only display the most common stats, that every API can fetch.

**Comment by jeroendesloovere** [comment]
@jessedobbelaere 
Your Mailmotor Dashboard request is something that is very custom per mail engine, f.e.: other data and  variable names. Even if we build a Shell for this, some other mail engines will not support or respond the same type of data. I suggest we look at this when the core is ready.

**Comment by GhaziTriki** [comment]
Why not creating a common API like what have been for https://github.com/thephpleague/omnipay then create depending libraries? It is a huge work to do but worth.

**Comment by jessedobbelaere** [comment]
Yes, some sort of adapter pattern so you can translate the interface of the uniform (mailmotor) functions to the interface of the mailchimp & campaign monitor API libraries (and make it easy to add a new service library). So you can use the well-known API libraries but translate them all to a uniform interface.

@jeroendesloovere You're right, but I mean to include only the most basic metrics that can be fetched by almost every mailservice. (And if there's a chance that a data value doesn't exist in the mailservice, it'll be null and won't be displayed.)

**Comment by jeroendesloovere** [comment]
Hi @GhaziTriki @jessedobbelaere,
I've started to create ```[mailmotor](https://github.com/mailmotor)``` which can hook any mail engine. The functionality will be similar to Omnipay, but for mail engines instead.

**Comment by jeroendesloovere** [comment]
@WouterSioen What do you think about minifying the mailmotor to its basics, so it can be used by all external mail services?

**Comment by WouterSioen** [comment]
I don't use the mailmotor module a lot, so I can't say if all features are used a lot.

I think you better ask more persons. @forkcms/core-contributors

**Comment by dubgeiser** [comment]
Maintainability of the mailmotor is indeed becoming a nightmare, which comes as no surprise, given the fact that for Campaign Monitor, Mailchimp and the likes, this is their core business.  Delegating as much as we can back to those services is a good idea IMO.

I think something like the following would be a great start:
I'm reducing services to Campaign Monitor (CM) for easier typing ;-)

CMS admin links mailmotor to CM
In the backend a list of groups is shown, admin can select which ones will be active on the website.
If more than one is selected, the admin can choose how these groups will be represented in the frontend: drop down, multi select, radio buttons, checkboxes.
A subscribe widget can be attached to pages, how the widget is rendered partly depends on the configuration (checkbox, etc...) and a template.
Subscriptions go directly to CM via API call, nothing is stored/cached in the Fork CMS database.

In a first iteration we build the linking of the account, the selection of the groups and the subscription widget; most of these things can be factored out of the current mailmotor module.
Then; either configuration of how the groups should be handled in the frontend, or support for multiple services.  The latter requires some analysis and design and some serious refactoring of what has been build in iteration 1, but should be possible due to the small scope of the required functionality.

My 0.02

**Comment by WouterSioen** [comment]
We discussed this in our @forkcms/core-contributors meeting.

We agree on reworking the mailmotor with less features and a common interface to couple different mailing systems.

We'd like at least this functionality:

- Coupling
- Subscriptions (also unsubscribe)
- Field management (Not only email, also First name, last name, ...)
- (backend) Group management
- (backend) Dashboard with all mailings and some stats
- (backend) Dashboard per mailing with some stats (opened, clicks, most clicked links,..)

These statistics are important for us, since we're a marketing minded CMS.

In a later iteration, it could be possible to write a separate module that builds and sends the mailings itself.

**Comment by MathiasDewelde** [comment]
:+1:

**Comment by WouterSioen** [comment]
@jeroendesloovere any news on this?

**Comment by jeroendesloovere** [comment]
@WouterSioen Didn't found the time to work further on it.

**Comment by jeroendesloovere** [comment]
Hi y'all.
Great news, the first version of the new "mailmotor" has been released.
Source: [mailmotor/fork-cms-module-mailmotor](https://github.com/mailmotor/fork-cms-module-mailmotor)

**Comment by jessedobbelaere** [comment]
Awesome, I'll test it with Mailchimp this weekend!

**Comment by WouterSioen** [comment]
Thats awesome, thx!

**Comment by jeroendesloovere** [comment]
When expanding the module in the future, we should definetly refactor the Gateway to support Member, List, ... instead of integrating all those functions in one gateway.

**Comment by ikoene** [comment]
Thx man, can't wait to take it for a spin :+1:

**Comment by WouterSioen** [comment]
@jeroendesloovere any news on this? Is this ready for a PR? It would be great to have this in the next major Fork release

**Comment by jeroendesloovere** [comment]
Hi @WouterSioen, would be awesome to have it in the next release.
I guess its ready to be used as it is.

We do need to discuss how we are going to be using the vendors.
At this moment, if you want MailChimp, you need to do:
1. ```composer require mailmotor/mailchimp-bundle```
2. Add code in your config.yml
3. Add parameters in your parameters.yml

Another approach would be (but currently not used):
```composer require mailmotor/mailmotor-bundle```
```composer require mailmotor/mailchimp-bundle```
```composer require mailmotor/campaignmonitor-bundle```

Out of the context:
Currently I'm having problems when deploying using Capistrano. The build says something like: "mailchimp.api_key not found ... Strange, because I do added it into the shared/app/config/parameters.yml file online...

**Comment by WouterSioen** [comment]
Ok, it would be nice if we could add the parameter trough the backend of Fork. I guess we'll need to create a small layer between the bundles (in the form of a module) that will set the needed parameters in the container. This can be done using a DependencyInjection class.

I think we'll also only need to load the bundles when the module is installed. I don't know if this is possible using these DependencyInjection classes.

Do you have time to create a pull request for this? If you need help, I'm willing to research some stuff if necessary.

Note that this should be PR'ed to the 3.10 branch, since this is Backwards Compatibility breaking stuff.

**Comment by jeroendesloovere** [comment]
@WouterSioen Done. Parameters are integrated in the new [MailMotor Module](https://github.com/mailmotor/fork-cms-module-mailmotor).

**Comment by jeroendesloovere** [comment]
Community, please test the new mailmotor (currently working with MailChimp) and give feedback.

**Comment by jeroendesloovere** [comment]
Does anybody has some feedback?
If none, then I will add PR for 3.10 branch

**Comment by jeroendesloovere** [comment]
@GhaziTriki Creating adapters is indeed a great work and therefore I choose not to do it like that. I did try to start this kind of thing. But I didn't know which functions would gonna be required to make all the subscribe/unsubscribe magic happen.
But your idea is good an perhaps something worth considering in the future when more functionalities are streamlined into interfaces.

**Comment by jeroendesloovere** [comment]
I'm not satisfied with the Class names in the Bundles. Thats why I'm going to refactor this into something like: https://gist.github.com/jeroendesloovere/958d5afe1f4f5b367f43

**Comment by jeroendesloovere** [comment]
Note: every mailmotor repo has a refactored branch.

**Comment by jeroendesloovere** [comment]
New PR #1629

**Comment by jeroendesloovere** [comment]
New PR #1831
