### ISSUE TITLE
Hooks/Events is not working

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1249]
Hi, I tried to use Hooks/Events but they are not working. Code just seems to be incomplete. First of all when you subscribeToEvent it serializes callback, later in the log it shows unserialized data. I was unable to make this to work.

**Comment by WouterSioen** [comment]
normally, you have to use the cronjob that executes the hooks, if I remember correctly, but I never used them myself.

**Comment by vytenizs** [comment]
Have this thing any docs, how to use them?

**Comment by WouterSioen** [comment]
I'd advise to use Symfony's event dispatcher instead of the Fork hooks, since we'll remove the hooks in favor of the event dispatcher. You can read how to implement them here:

https://woutersioen.github.io/Symfony-components-in-fork/#36 (Fork specific)

and

http://symfony.com/doc/current/components/event_dispatcher/introduction.html (More info, but in a Symfony setting).

The FormBuilder module uses them in the frontend, so you can take a look there.


I was also planning on writing a blogpost on the Fork CMS website about this soon.

**Comment by vytenizs** [comment]
Ok thanks. You can close this issue. Thought this is not yet implemented.
