### ISSUE TITLE
Last item in breadcrumb must have a link

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1309]
By default the link from the last breadcrumb item is removed. I think you should decide this in your template. Based on the client needs you can either set the url or remove it.

**Comment by WouterSioen** [comment]
Why would you want a url to the page you're currently on?

**Comment by jacob-v-dam** [comment]
I thought it would be nice to have with the [breadcrumb structured data] (https://developers.google.com/structured-data/breadcrumbs). By this Google (and maybe others) will also display the last element of the breadcrumb in the search results.

An example on a existing site (currently the breadcrumbs are broken, i will fix this today):
https://www.google.nl/?gws_rd=ssl#q=buro+boot+asbest

As you can see: The full path is shown

**Comment by WouterSioen** [comment]
You're right, this looks nice.

Can you make a pull request for this? You can change the abscense of the url here: https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/Breadcrumb.php#L157

I would still change this template too: https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Layout/Templates/Breadcrumb.tpl to still not inlcude the link by default (so changing `{option:breadcrumb.url}` to `{option:!breadcrumb.last}`)
This is needed to preserve backwards compatibility. We don't want the existing themes to change automatically because of this.

**Comment by jacob-v-dam** [comment]
Would you als like to see the structured data in the default template? It could boost the value of Fork CMS in my opinion.

**Comment by WouterSioen** [comment]
That would be nice, yes!

**Comment by jeroendesloovere** [comment]
:+1:

**Comment by jeroendesloovere** [comment]
@jacob-v-dam Has created PR #1313
