### ISSUE TITLE
Issue and pull request templates

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1406]
As per suggestion by @jeroendesloovere on Slack
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by WouterSioen** [comment]
a PR is welcome :)

**Comment by jeroendesloovere** [comment]
:+1:

**Comment by carakas** [comment]
What do I need to include in the templates ? Any suggestions ?

**Comment by GhaziTriki** [comment]
The issue template can contain the following items:

**Severity**: Trivial, Minor, Major, or Blocker

**Steps to Reproduce**

1. Step one
2. Step two

**Actual Behavior**

Behave strangely.

**Expected Behavior**
Should behave correctly.

**Troubleshooting/Testing Steps Attempted**
A long night debugging and I put my cat over my keyobard and it worked !!!

**Comment by WouterSioen** [comment]
that's a good start

**Comment by jeroendesloovere** [comment]
I would minimalize it to tree steps:

**Problem?**
**Steps to reproduce**
**Expected behavior/Proposed solutions**
