### ISSUE TITLE
replace all cronjobs with cli commands.

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1631]

**Comment by jeroendesloovere** [comment]
Are there cronjobs in the Fork CMS Core?

**Comment by WouterSioen** [comment]
there were at least.

**Comment by WouterSioen** [comment]
but I would even remove the possibility to use cronjobs through http.

**Comment by jacob-v-dam** [comment]
It would be nice if you can register an cronjob via the module to one cronjob handler. Just call one script which handles all the cronjob actions.

By this you could set the runtime of each job within the module.

**Comment by carakas** [comment]
I'm not really in favour of a master cronjob, I prefer multiple small ones, that way the control stays in the hands of the user

**Comment by carakas** [comment]
@jacob-v-dam also if one cronjob crashes in that handler it might take down all the cronjobs with it

**Comment by tijsverkoyen** [comment]
In the pre-open-source version of Fork there was a system which only required 1 cronjob every minute. In the code it was calculated which registered cronjob should be executed.

We removed it for several reasons:
* You have to manage concurring jobs, eg: when a jobs is ran every minute, but the execution-time spans more then a minute.
* You have to implement a system that notifies someone on errors
* In general you are just reinventing a `crontab` system

I think the commands are the way to go, because they have support for multiple systems.

@WouterSioen I don't have any knowledge of any existing cronjobs, except for the one that is supposed to handle the hooks-queue, but I think this whole system should be removed in 5.0
