### ISSUE TITLE
Security - forgot passoword leaks if the email is linked to a backend account

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1657]
## Type

- Security issue

## Problem description

> The password forgot of the backend gives too much information, you can add email addresses and get a message if the email address is in the database

## Steps to reproduce

> Press the `Forgot password?` link on the login page of the backend

## Expected behavior / Proposed solutions

I think it should always return the same message, something like: if your email address is known to us, you should get your password reset mail soon

**Comment by StijnVrolijk** [comment]
The only issue I see with your solution is that if someone were to make a typo ( such as info@project.com instead of info@project.net ) they might wait endlessly for an email to arrive which was never sent in the first place. When this happens, guess what they're reaction is? Yeah it's "Hey mister developer, I found a bug! I can't reset my password!".

Of course we all know you can't fix stupid.

**Comment by carakas** [comment]
you can add a warning that they need to be sure they type it correctly? :p It is a fine line between security and user friendliness

**Comment by StijnVrolijk** [comment]
That's kind of my point. I think this is a nudge too far towards security.
Even though there is this minor security flaw, I haven't heard of too many Fork websites that have been hacked let alone the backend.

I think our time is better spent in preventing bruteforcing which has little to no influence on user experience.

**Comment by carakas** [comment]
ok, I'll close this issue
