### ISSUE TITLE
FormBuilder: CSS class cannot be set for "submit" field

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1736]
## Type
- Enhancement
## Problem description

When implementing some themes, setting the CSS class property for the "submit" field.
## Steps to reproduce

Edit the submit field of a form.
## Expected behavior / Proposed solutions

Add classname property to submit field.

**Comment by GhaziTriki** [comment]
It could be awesome if it can also be done for "Heading" text element.

**Comment by carakas** [comment]
will be fixed in #1930

**Comment by tijsverkoyen** [comment]
This can be done by overruling the template from within a theme. You should overrule the template: `/src/Frontend/Modules/FormBuilder/Layout/Widgets/Form.html.twig`

In v5 this will become easier, as the themes can/will be simpler, since we started using the Twig-block, you can extend these templates.

As an example we have the default markup for the TagCloud-widget, which is:

    {% if widgetTagsTagCloud %}
      <aside class="module-tags widget-tags-tag-cloud">
        {% block widgetHeading %}
          <header class="widget-heading" role="banner">
            <h3>{{ 'lbl.Tags'|trans|ucfirst }}</h3>
          </header>
        {% endblock %}

        {% block widgetBody %}
          <div class="widget-body">
            <p>
              {% for tag in widgetTagsTagCloud %}
                <a href="{{ tag.url }}" rel="tag">
                  {{ tag.name }}
                </a>
                <span class="badge hidden-phone">{{ tag.number }}</span>{% if not loop.last %},{% endif %}
              {% endfor %}
            </p>
          </div>
        {% endblock %}
      </aside>
    {% endif %}

As you can see there is a `widgetHeading`-block. So if your theme doesn't need a header, your code in your theme would be:

    {% extends "@ForkFrontendModules/Tags/Layout/Widgets/TagCloud.html.twig" %}

    {% block widgetHeading %}
    {% endblock %}

As you can see we are extending the default-template, and overrule the `widgetHeading`-block.
