### ISSUE TITLE
Media library: folder name longer than one word

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2565]
## Type

- Non critical bug

## Problem description

The white spaces from a folder with a name longer then one word got replaced by -

## Steps to reproduce

Add a folder with a name longer then one word.
You can see the issue in the folder tree or when you edit the folder

**Comment by jeroendesloovere** [comment]
Hi @Katrienvh 

So, if I'm correct, what you want is that we do not urlize "folder names" anymore?

**Comment by StijnVrolijk** [comment]
@jeroendesloovere why not seperate the name and the url? A folder with whitespaces in it is a perfectly valid folder, the URI should not influence the name of the folder

**Comment by Katrienvh** [comment]
What Stijn says is exactly my point: the URI should not influence the name of the folder

**Comment by jeroendesloovere** [comment]
## A little history

One of the reasons why I decided to go for "URI"-name instead of a "name",
was that it was easier to have if somebody wanted to create custom integrations like f.e.: moving all media library files to **folders** on another FileSystem of using Cloud services like Amazon, Dropbox, ...

But currently "URI" seems obsolete.
And since I haven't heard anybody doing such things... which require "urlized" folder name.

## Conclusion: proposed solution

The database field in `MediaFolder` is called `name`.
=> We can remove the urlisation entirely and start using "normal names".
=> Backwards compatible.
