### ISSUE TITLE
Media Galleries: widget location doesn't make sense

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2569]
## Type
- Non critical bug

## Problem description

The explenation in fork:

> As a developer, you can add your own custom widgets by adding them in the folder /src/Frontend/Modules/MediaLibrary/Widgets/. Each widget that you add gets added in this dropdown automatically and can have its own image sizes in the Frontend.

Why are media gallery widgets added to the media library??? it doesn't make sense!

**Comment by jeroendesloovere** [comment]
I use this every time and it works...
Can you tell me exactly what you did?

**Comment by Katrienvh** [comment]
I updated my issue

**Comment by jeroendesloovere** [comment]
I'm sorry, but I don't understand.
Can you give a little more information please.

**Comment by jeroendesloovere** [comment]
Ah you probably mean, why you must put your "custom media library widgets" in the "MediaLibrary" and not in the "MediaGalleries" directory.

**Comment by carakas** [comment]
@jeroendesloovere before you close the issue first check with @Katrienvh if that answer solves the issue for her

**Comment by StijnVrolijk** [comment]
@jeroendesloovere isn't the entire point of the `MediaGalleries` module to have several ways to display media stored in the `MediaLibrary` module?

Imo there's a conflict of responsibilities here.
`MediaLibrary`'s only responsibility should be to store and manage media, not decide how it gets displayed. Therefor having widgets in the `MediaLibrary` is inherently incorrect, I think.

I get where you're coming from, but I think other modules should access the `MediaGalleries` module to add media widgets to themselves, not the `MediaLibrary` module.

**Comment by Katrienvh** [comment]
I agree with stijn, that other modules should access the MediaGalleries module not Media Library, that make more sense to me

**Comment by jeroendesloovere** [comment]
@StijnVrolijk & @Katrienvh 

## MediaGalleries module
The MediaGalleries module is just build as an example module in how you can extend the MediaLibrary MediaGroup and how to use `MediaGroupType` in a symfony form.
So everybody can see how to integrate MediaLibrary in their custom modules (blog, news, jobs, whitepapers, downloads, realizations, projects, banners, ...).

## Solution for your question
I do made it possible for everybody to place "custom widgets" in "their own custom modules directories".
Hereby I refer to the $module declaration in the Twig `media_library_widget` method https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/MediaLibrary/Twig/Extensions/FrontendHelperExtensions.php#L45

So we could make "small modifications" to the "MediaGalleryAdd/Edit" dropdown to find "custom widgets" in the "/src/Frontend/Modules/**MediaGalleries**/Widgets" (and not only in the MediaLibrary directory).
**But** I insist that the default media library widgets remain on their place in the MediaLibrary widget, since that is the "core" for everything (and MediaGalleries is just an example module).

**Comment by carakas** [comment]
@jeroendesloovere can you use the widgets in the media library without installing the media gallery?
If so can you give us an example of this

**Comment by jeroendesloovere** [comment]
@carakas Yes, off course you can. That is the entire principle of the Media Library.

I strongly advice you guys read this documentation page
https://github.com/forkcms/forkcms/blob/master/docs/07.%20media%20library/03.%20integrating%20in%20your%20module.md

**Comment by jeroendesloovere** [comment]
And specifically the Frontend section
https://github.com/forkcms/forkcms/blob/master/docs/07.%20media%20library/03.%20integrating%20in%20your%20module.md#integration-in-frontend

**Comment by StijnVrolijk** [comment]
@jeroendesloovere I've reread everything (took over 2 years, whew) and decided nothing has to change. I understand now.
